version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root # <--- Important pour avoir les permissions d'exécuter docker
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false 
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # <--- Accès au Docker de ta machine
    networks:
      - jenkins_network
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
